// generated by `$ scala-cli --power fix .` command

// Main
// scala-cli tries to run *.sc files as scripts and complains about it
//> using exclude "./src/scratch.sc"

// Test
// place all tests in 'test' directory
//> using test.dependency "org.scalameta::munit::1.0.0"
